{{ if and .Values.configmap.enabled .Values.configmap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kontroller.fullname" . }}
  labels:
    {{- include "kontroller.labels" . | nindent 4 }}
data:
{{- with .Values.configmap.data }}
{{ toYaml . | indent 2 }}
{{- end }}
{{ end }}
