{{ if .Values.ingress.enabled }}
{{- $fullName := include "kontroller.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kontroller.fullname" . }}
  labels:
    app: {{ include "kontroller.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "kontroller.fullname" . }}
    helm.sh/chart: {{ include "kontroller.chart" . }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
{{ if and .Values.ingress.subdomain .Values.ingress.basedomain }}
    - host: {{ .Values.ingress.subdomain }}.{{ .Values.ingress.basedomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
{{ end }}
{{ range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
{{ end }}
{{ end }}