{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kontroller.fullname" . }}
  namespace: {{ include "kontroller.namespace" . }}
  labels:
    {{- include "kontroller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kontroller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kontroller.serviceAccountName" . }}
    namespace: {{ include "kontroller.namespace" . }}
{{- if .Values.kollector.rbac.create }}
  - kind: ServiceAccount
    name: {{ include "kollector.serviceAccountName" . }}
    namespace: {{ include "kollector.namespace" . }}
{{- end}}
{{- end }}