apiVersion: v1
kind: Service
metadata:
  name: {{ include "kontroller.fullname" . }}
  labels:
    {{- include "kontroller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
  {{- end}}
  selector:
    app:   {{- include "kontroller.selectorLabels" . | nindent 4 }}

