
fullnameOverride: "kontroller"
nameOverride: ""

replicaCount: 1

profile: default

image:
  repository: ghcr.io/opsnowsecurity/scarif-kontroller
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

imagePullSecrets: []
# - name: regcred

ingress:
  enabled: false
  subdomain: kontroller
  basedomain: ""  # 사용자 입력값
  hosts: {}
  annotations:
    kubernetes.io/ingress.class: nginx
  #  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #  nginx.ingress.kubernetes.io/whitelist-source-range: 58.151.93.2/32,58.151.93.9/32,14.177.235.12/32
  labels: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  annotations: {}
  labels: {}

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # Image pull secrets that are attached to the ServiceAccount
  imagePullSecrets: []
  # Automount API credentials for the Service Account
  automountServiceAccountToken: true

command: []
# - "/bin/sh"
# - "-c"
args: []
# - ". /vault/secrets/config && exec java $JAVA_OPTS -jar ROOT.jar"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  readOnlyRootFilesystem: false
  procMount: Unmasked

hostNetwork: false
dnsPolicy: ClusterFirst

terminationGracePeriodSeconds: 60

podDisruptionBudget: {}
#  maxUnavailable: 1
#  minAvailable: 1

health:
  enabled: true

readinessProbe: {}
#  httpGet:
#    path: /
#    port: http
#  initialDelaySeconds: 60
#  periodSeconds: 10
#  failureThreshold: 3

livenessProbe: {}
#  httpGet:
#    path: /
#    port: http
#  initialDelaySeconds: 60
#  periodSeconds: 10
#  failureThreshold: 3

startupProbe: {}
#  httpGet:
#    path: /
#    port: http
#  initialDelaySeconds: 15
#  timeoutSeconds: 1
#  failureThreshold: 60
#  periodSeconds: 5

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# load envFrom
configmap:
  enabled: false
  data: {}
  # MESSAGE: "hello world"

# load envFrom
secret:
  enabled: false
  data: {}
  # SECRET: "c2VjcmV0IHdvcmxkCg=="

env: []
#- name: JAVA_OPTS
#  value: -XX:InitialRAMPercentage=40.0 -XX:MaxRAMPercentage=80.0

envFromConfigMaps: []
## - name: configmap-name
##   optional: true

envFromSecrets: []
## - name: secret-name
##   optional: true

## Array of extra Kubernetes manifests, in form of YAML object,
## if you want to deploy
extraObjects: []
#- apiVersion: v1
#  kind: ConfigMap
#  metadata:
#    name: '{{ template "opsnow.fullname" . }}-extra-config'

## Array of extra Kubernetes manifest, in form of template string,
## if you want to deploy
extraTemplates: []
#- |
#  apiVersion: external-secrets.io/v1beta1
#  kind: ExternalSecret
#  metadata:
#    name: sample-external-secret
#    labels:
#   {{- include "opsnow.labels" . | nindent 4 }}
#  spec:
#    dataFrom:
#    - extract:
#        conversionStrategy: Default
#        decodingStrategy: None
#        key: sre/sre-sample-projects/dkc
#      rewrite:
#        - regexp:
#            source: sre/sre-sample-projects/dkc/(.*)
#            target: $1
#    refreshInterval: 1h
#    secretStoreRef:
#      kind: ClusterSecretStore
#      name: sre
#    target:
#      creationPolicy: Owner
#      deletionPolicy: Retain
#      name: sample-secret

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  volumeName: opsnow-security-pv
  claimName: opsnow-security-pvc
#  storageClassName: "-"
  accessModes:
    - ReadWriteOnce
  size: 10Mi
  # annotations: {}
  selectorLabels: {
    name: opsnow-security-pv
  }
  ## Sub-directory of the PV to mount. Can be templated.
  # subPath: ""
  ## Name of an existing PVC. Can be templated.
  # existingClaim:
  ## Extra labels to apply to a PVC.
  extraPvcLabels: {
    name: opsnow-security-pvc
  }
  extraPvLabels: {
    name: opsnow-security-pv
  }
  hostPath:
    path: /mnt/logs
    type: DirectoryOrCreate

# -- Additional volumeMounts to the server main container
volumeMounts: []
#  - mountPath: /usr/local/bin/kubelogin
#    name: custom-tools
#    subPath: kubelogin

# -- Additional volumes to the server pod
volumes: []
#  - name: custom-tools
#    emptyDir: {}

rbac:
  create: true
  clusterRole:
    extraRules: []
  role:
    extraRules: []

common:
  authUrl: "https://scarif-kspm.auth.ap-northeast-2.amazoncognito.com/oauth2/token"

versioncheckInterval: 60m
versionRetryInterval: 30s

kontroller:
  gracefulShutdownTimeout: "60"
  persistence:
    enabled: false

kollector:
  image:
    repository: ghcr.io/opsnowsecurity/scarif-kollector:latest
    pullPolicy: Always
    katcherUrl: "http://mock-katcher-service.opsnow-security.svc.cluster.local:33455"
  persistence:
    enabled: true
  resources: {
    limits: {
      cpu: 520,
      memory: 200
    },
    requests: {
      cpu: 200,
      memory: 50
    }
  }
  
  # 향후 제거 예정
  statusInterval: 10m
  gracefulShutdownTimeout: "5"

  serviceAccount:
    create: true
    name: opsnow-security
  rbac:
    create: true